### ISSUE TITLE
Search Query must be set before Search Category

### ISSUE THREAD

**Issue by sarahsporck** [matomo-org/matomo-java-tracker#133]
The Request builder first sets the search category and then the search query. This leads to this error.
https://github.com/matomo-org/matomo-java-tracker/blob/1fdf79e44c104cfb3325a393abaf59e09dbc17ae/src/main/java/org/matomo/java/tracking/MatomoRequestBuilder.java#L586-L591

**Comment by tholu** [comment]
@sarahsporck Can you create a Pull Request to fix this?
