### ISSUE TITLE
[REQUEST] pom.xml of releases should contain correct version numer

### ISSUE THREAD

**Issue by rafaelorafaelo** [matomo-org/matomo-java-tracker#196]
**Is your feature request related to a problem? Please describe.**
Your pom.xml files of release 3.2.0 an earlier contain the version number of the next development snapshot like this: `<version>3.2.1-SNAPSHOT</version>`

**Describe the solution you'd like**
Released pom.xml files should contain the correct version number: <version>3.2.0</version>. Example: https://github.com/jetty/jetty.project release 12.0.5 pom.xml files contain `<version>12.0.5</version>`

**Describe alternatives you've considered**
n/a

**Additional context**
When I build the current release, my built JAR files are named 3.2.1-SNAPSHOT. Mavens .m2 repository cache contains Matomo dirs named 3.2.1-SNAPSHOT. It's very confusing, which version is built.

**Comment by dheid** [comment]
Sorry, that's how Maven versioning works. It's the usual flow and we won't change that. Check out a release tag, if you want to build a published version.
