### ISSUE TITLE
Renamed project to matomo-java-tracker

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo-java-tracker#34]
Hi @tholu @bcsorba - I've thought i'd go ahead and just renamed the project to `matomo-java-tracker` - the old url automatically redirects: https://github.com/matomo-org/piwik-java-tracker

Let me know if there's any problem or question. 

also @tholu could you reach out at hello@matomo.org or share your email address with us somehow? i wanted to share an info. Thanks

**Comment by tholu** [comment]
@mattab Just sent you an email, thanks for renaming, will clean up the references in README.
