### ISSUE TITLE
Bulk request is not working - PiwikTracker

### ISSUE THREAD

**Issue by dostonhamrakulov** [matomo-org/matomo-java-tracker#36]
BulkRequest is not performing a request. I have sent `Iterable<PiwikRequest>` list to `new PiwikTracker(matomoSeverUrl).sendBulkRequest(requests);` and I got 200 status code, but actually no data is sent to Matomo server. 

Here is the example:

`
        
        import org.apache.http.HttpResponse;
        import org.piwik.java.tracking.PiwikRequest;
        import org.piwik.java.tracking.PiwikTracker;
        import org.slf4j.Logger;
        import org.slf4j.LoggerFactory;
        
        import java.io.IOException;
        import java.net.URL;
        import java.util.ArrayList;
        import java.util.Collections;
        import java.util.List;
        
        public class Example {
        
            private static final Logger LOGGER = LoggerFactory.getLogger(Example.class);
        
            final String matomoTrackingUrl = "MATOMO_SERVER_URL";
            final int matomoSiteId = 1;
            
            public void sendToMatomo(final ObjectEntity objectEntity) {
                makeRequest(buildRequest(objectEntity), null);
            }
            
            public void sendToMatomoBulk(final List<ObjectEntity> statusLogEntities) {
                final List<PiwikRequest> piwikRequests = new ArrayList<>();
        
                statusLogEntities.forEach(objectEntity -> {piwikRequests.add(buildRequest(objectEntity));});
        
                piwikRequests.removeAll(Collections.singleton(null));
                makeRequest(null, piwikRequests);
            }
        
            private void makeRequest(final PiwikRequest piwikRequest, final Iterable<PiwikRequest> piwikRequests) {
                try {
                    final PiwikTracker tracker = new PiwikTracker(matomoTrackingUrl);
                    HttpResponse httpResponse = null;
        
                    if (piwikRequest != null) {
                        httpResponse = tracker.sendRequest(piwikRequest);
                    }
        
                    if (piwikRequests != null) {
                        httpResponse = tracker.sendBulkRequest(piwikRequests);
                    }
        
                    if ((httpResponse != null) && (httpResponse.getStatusLine().getStatusCode() != 200) &&
                            (httpResponse.getStatusLine().getStatusCode() != 204)) {
                        LOGGER.error("Request to Matomo server failed with status code: " +
                                httpResponse.getStatusLine().getStatusCode() + " and reason phrase: " +
                                httpResponse.getStatusLine().getReasonPhrase());
                    }
                } catch (final IOException e) {
                    LOGGER.error("Cannot send a request to Matomo Server.", e);
                }
            }
        
            private PiwikRequest buildRequest(final ObjectEntity objectEntity) {
                try {
                    final URL actionUrl = new URL(matomoTrackingUrl);
        
                    final PiwikRequest request = new PiwikRequest(matomoSiteId, actionUrl);
                    
                    // .. other settings
        
                    return request;
                } catch (final IOException e) {
                    LOGGER.error("Cannot build a request for the given status log entity.", e);
                }
        
                return null;
            }
        }

`

I have made a single request by iterating the list and it works well. Could you please confirm if this is bug ? or did I have something wrong?

Thank you.

**Comment by ccpena** [comment]
Hi, 

Did you try passing the token through the `sendBulkRequestion` function?

**Comment by dostonhamrakulov** [comment]
Hi,
Thanks for your reply.
 I have tried to send token_auth, but no changes 😞😞

**Comment by tholu** [comment]
@dostonhamrakulov Which version are you using?

**Comment by dostonhamrakulov** [comment]
I am using the version 1.2
`        

       <dependency>
            <groupId>org.piwik.java.tracking</groupId>
            <artifactId>piwik-java-tracker</artifactId>
            <version>1.2</version>
        </dependency>`

**Comment by tholu** [comment]
@dostonhamrakulov Some work was done also on the bulk requests for the upcoming release (including async support), will release this as soon as possible.

**Comment by dostonhamrakulov** [comment]
@tholu Thank you for your support. We look forward to seeing the upcoming release. Can we keep this issue open until the problem is resolved?

**Comment by tholu** [comment]
@dostonhamrakulov Sure!

It should actually be there soon, check out: https://search.maven.org/artifact/org.piwik.java.tracking/matomo-java-tracker/1.5/jar

**Comment by dostonhamrakulov** [comment]
@tholu actually I did not notice before that you have changed the artifact ID to ```<artifactId>matomo-java-tracker</artifactId>``` and now I can import the dependency.

Unfortunately, the bulk request is still not working, I have tested  ```sendBulkRequestAsync``` with and without auth token. However, I have to admit the single asynchronous request is working wonderful. Have you tested it? and is it working on your side? (in your test cases).

**Comment by tholu** [comment]
@dostonhamrakulov The project name changed, so the artifact ID changed as well. The changes for 1.5 were made before this issue was created, and I wanted to make sure that it is still present, before we investigate further. Will check and add some tests for it!

**Comment by dostonhamrakulov** [comment]
@tholu okay, I got it. I hope you will start investigating soon and resolve the problem so that we go also further in our development. 

One more wish from our side is to have a possibility to add ```custom dimensions``` in the request, it would be great to see this feature in the upcoming releases. Since the current release does not have this feature, we are using ```custom variables (visit custom variable)```, but as you may know, due to the difference between ```custom dimensions``` and ```custom variables```, we would love to use ```custom dimensions```.

**Comment by dostonhamrakulov** [comment]
Hi guys, could you please tell anything new in this issue?

**Comment by tholu** [comment]
@dostonhamrakulov I tried to reproduce your issue with the code provided above with the latest version, but I can't reproduce it. The requests are sent just fine.

Please create a new issue regarding the `custom dimensions.
