### ISSUE TITLE
Compatibility with Matomo 4

### ISSUE THREAD

**Issue by tsteur** [matomo-org/matomo-java-tracker#39]
Hi there,

this issue refs https://github.com/matomo-org/matomo/issues/16397#issue-694540064

in Matomo 4 we're changing the structure of the visitor cookie. I don't know if this SDK reads the cookie of a visitor if one is set? 

In the PHP tracker we had to make this change because of it https://github.com/matomo-org/matomo-php-tracker/pull/79/files#diff-cd22a4ca6eb55e6a5ad813334624ed89L1370-L1840

The cookie was changed in https://github.com/matomo-org/matomo/pull/15774/files#diff-1279d666063b65e6d6777f902d11574fR3322-R3330

It used to contain 6 indexes (newVisitor, uuid, createTs, visitCount, currentVisitTs, lastVisitTs) but now contains only indexes:
Slot 0: newVisitor
Slot 1: uuid
Slot 2: createTs

Basically, if this tracker does read the cookie, then the tracker needs to be changed to only read the first to slots from the cookie (cookieVisitorId and createTs) see https://github.com/matomo-org/matomo-php-tracker/pull/79/files#diff-cd22a4ca6eb55e6a5ad813334624ed89L1370-L1840

All other information from the cookie list visit count, currentVisitTs, lastVisitTs is no longer needed in Matomo 4. 

If this tracker does not read any cookies then it can be ignored.

**Comment by dheid** [comment]
Hi @tsteur! I analyzed the code and there was no cookie reading. Nevertheless I added it to read the existing cookies described in https://matomo.org/faq/general/faq_146/. Closing this issue, since there is nothing to do.
