### ISSUE TITLE
Event list inside Behaviour section is not showing all events

### ISSUE THREAD

**Issue by thiagofabre** [matomo-org/matomo-java-tracker#46]
## Issue
For some reason, the events are not showing in the Event list inside Behaviour section, but I can see them on the Visitors Log

Here you can see the list of actions with 6 actions
![Screenshot from 2021-02-18 17-15-49](https://user-images.githubusercontent.com/6961049/108395583-dba38480-720d-11eb-8e44-a8b421b65e95.png)

Here you can see the events has only 3 entries
![Screenshot from 2021-02-18 17-17-10](https://user-images.githubusercontent.com/6961049/108395599-e1996580-720d-11eb-8d1f-527cba0e6c90.png)

## Your Environment

- Matomo Version: 4.1.1
- Matomo Tracker Java Library: 1.5
- PHP Version: 7.4.15
- Operating System: Ubuntu

**Comment by diosmosis** [comment]
duplicates https://github.com/matomo-org/matomo/issues/17232
