### ISSUE TITLE
Ignore SSL Validation

### ISSUE THREAD

**Issue by thiagofabre** [matomo-org/matomo-java-tracker#51]
Hi guys!
Is there any way to ignore SSL validation using the `PiwikTracker`?
I want to disable to test this in my Test Environment but getting the following expectation:
`javax.net.ssl.SSLPeerUnverifiedException: Hostname does not match the certificate subject provided by the peer`

**Comment by thiagofabre** [comment]
Looking at code maybe I can extend the `PiwikTracker` and override the `getHttpAsyncClient()` with a new HttpAsyncClient that ignores SSL. DO you guys think this is the best way?

**Comment by tholu** [comment]
@thiagofabre Feel free to try it out - you can also provide a Pull request, happy to review & release it soon as well.

**Comment by tholu** [comment]
@thiagofabre Did that work?
