### ISSUE TITLE
Support callback in async send methods

### ISSUE THREAD

**Issue by ssaarinen** [matomo-org/matomo-java-tracker#55]
Using `MatomoTracker#sendRequestAsync` method there is no easy way for caller to know if the call succeeds other than calling response.get(...) that causes calling thread to block and makes it effectivelly same as `sendRequest `. 

Consider allowing clients to pass callback to HttpAsyncClient execute from `MatomoTracker#sendRequestAsync` et. al.

**Comment by tholu** [comment]
@ssaarinen Can you provide a Pull request for that?

**Comment by ssaarinen** [comment]
If the PR (#56) is fine could you maybe consider releasing the 1.7 version including it in the near future :) ?

**Comment by tholu** [comment]
@ssaarinen Thanks, I have merged it now and will prepare the 1.7 version next.

**Comment by tholu** [comment]
@ssaarinen v1.7 is on its way to Maven Central and I tagged a release: https://github.com/matomo-org/matomo-java-tracker/releases/tag/v1.7
