### ISSUE TITLE
Event Appearing as Custom Variable in Matomo Dashboar

### ISSUE THREAD

**Issue by aashishgoyal2000** [matomo-org/matomo-java-tracker#60]
I am sending events using Piwik Tracker with the sendBulkRequestAsync method, and the event is appearing as Custom Variable in the dashboard. It should appear in the events list.

{
"eventName":"Name: ",
"eventAction":"Action",
"eventCategory":"Category",
"eventValue":null,
"eventTime":1655388962709
}

Events are being raised from Spring Boot Java using Piwik Tracker.
Dependency Used:

org.piwik.java.tracking
matomo-java-tracker
1.7

**Comment by dheid** [comment]
@aashishgoyal2000 Could you please provide the code that creates the request?

**Comment by tholu** [comment]
@aashishgoyal2000 Closed due to inactivity. Feel free to reopen.
