### ISSUE TITLE
Complete rewrite

### ISSUE THREAD

**Issue by dheid** [matomo-org/matomo-java-tracker#65]
Hi @tholu!

I did a complete rewrite of the library just for fun: https://github.com/dheid/matomo-tracker

It does not have any dependencies, has less code and is easier to maintain. There is no benchmark, but it could be a little bit faster / less memory consuming.

Perhaps we can think about merging the two projects together? I don't know if the users of your library will like this.

What do you think?

**Comment by tholu** [comment]
@dheid Wow, that looks awesome! I don't really own this project here, I just got maintainer rights when I fixed one of my issues back then.

Maybe ask in the Matomo Slack community?

**Comment by dheid** [comment]
Nobody answers. Perhaps it's good to be able to choose between different implementations.

**Comment by tholu** [comment]
@dheid That's unfortunate. I would still support merging the two projects as a new major version. We can also link to your implementation in the README 👍

**Comment by mattab** [comment]
Hi @dheid, @tholu,

Thanks for your patience (one year ago already :see_no_evil: ), I just now see your message, really sorry that we missed it earlier.

Your project & work looks great, so well done! :muscle: 

 @tholu Nice to read that you would support merging the two projects as a new major version breaking BC.

-> If you are both still interested, then maybe we could progress with merging the two projects here? (I can give you the access to this repo). 

And thanks once again both for your proactive approach and contributions. Looking forward to further discussions.

**Comment by dheid** [comment]
Hi @mattab ! That would be great! 👍

**Comment by mattab** [comment]
Hi @dheid - nice to hear! You're now "Maintainer" on this repo 🙌  
maybe you can discuss next steps with @tholu 
and if you need "Admin" permission for this repo at some point, let us know. Happy hacking!

**Comment by dheid** [comment]
Thanks! I will discuss the next steps with @tholu

**Comment by dheid** [comment]
@tholu are you on Discord or something?

**Comment by tholu** [comment]
@dheid You can find me in the Matomo Slack, try to direct message me there.

**Comment by dheid** [comment]
@tholu Could you please invite me there? mail@daniel-heid.de

**Comment by dheid** [comment]
@mattab Hi Matthieu! Thanks for adding me to the Matomo Java Tracker. I talked to @tholu  and we decided to first do a release of the bugfixes in the current version. He wants me to do the release. Could you please give me the permissions to push the artifact to Maven Central? My OSS user is "dheid"
